### ISSUE TITLE
Add reference to PHP session storage in the README

### ISSUE THREAD

**Issue by daserzw** [jornane/mwSimpleSamlAuth#21]
If do not set correctly $wgSessionName in the LocalSettings.php of mediawiki (ie "$wgSessionName = ini_get('session.name');") the extension will never work... so maybe it is a good idea to state it clearly in the README :-)

**Comment by jornane** [comment]
I have no reference to `$wgSessionName` in my code, so i'm curious what goes wrong in your case.

**Comment by daserzw** [comment]
Hi Jørn, 

the $wgSessionName is referenced on the mediawiki.com page of your (!) Extension. In the page the comment says "make sure that session storage matches to the one used in simplesaml most likely default PHPSESSID". Before setting the variable, after a successful authentication I had very awkward logs from simplesamlphp:

Oct 30 16:29:21 XXXXX simplesamlphp[4319]: 7 [55fc27a1d7] Session: doLogin("default-sp")
Oct 30 16:29:21 XXXXX simplesamlphp[4319]: 7 [0199d11742] Session: 'default-sp' not valid because we are not authenticated.

It seems that the authentication was successful for the session, but then whenever I was redirected to the wiki, a new session was created and that one was not authenticated! I gone mad looking around for a solution, and then I had a look on the page on mediawiki.com and I found out that  maybe I was missing the $wgSessionName setting (also referenced here: https://syferlock.zendesk.com/hc/en-us/articles/206444477-SimpleSAMLAuth-Extension).
BTW I didn't set the session storage in simplesamlphp to anything, I just used the default.

Cheers
Davide

**Comment by jornane** [comment]
"the $wgSessionName is referenced on the mediawiki.com page of your (!) Extension"

Heh, some anonymous user added that last Wednesday. The thing is, I can imagine this fixing everything in some cases, and I can also imagine this breaking everything in some cases. In any case, the default value for SimpleSamlPHP is `"SimpleSAMLSessionID"`, not `ini_get('session.name')` or `"PHPSESSID"`, so I want to have to test around a bit. I **think** SimpleSamlPHP ignores its own session name when not using memcache and uses `ini_get('session.name')` instead, which makes the change you proposed work for you.

I'll check back tomorrow.

**Comment by jornane** [comment]
Yep, SimpleSamlPHP uses a different session name depending on the session backend. I'll check out if it's possible to "ask" SimpleSamlPHP so that the extension can set the correct session name for MediaWiki. If not, then this behaviour should be documented so that the wiki admin can set the appropriate session name.

**Comment by daserzw** [comment]
Thanks a lot Jørn . If I understand well, I can stick to `ini_get('session.name')` for `$wgSessionName` until I decide to use memcache as a session storage, am I right?

**Comment by jornane** [comment]
Yes, if you use PHP session storage on *both* SimpleSamlPHP *and* MediaWiki (which is the standard setting for both), `ini_get('session.name')` is the correct value.

**Comment by jornane** [comment]
I think I got it.

* If both SSP and MW use PHP sessions, `$wgSessionName` MUST be `ini_get('session.name')`.
* If SSP uses PHP and MW uses memcache, `$wgSessionName` MUST NOT be `ini_get('session.name')`.
* If SSP uses memcache and MW uses PHP, `$wgSessionName` is not important (as long it's not `"SimpleSAMLSessionID"`)
* If both SSP and MW use memcached,  `$wgSessionName` is not important (as long it's not `"SimpleSAMLSessionID"`)

Shorter said, if MW uses PHP sessions, `$wgSessionName` MUST be `ini_get('session.name')`, otherwise it MAY be.

```php
if(!$wgSessionName && !$wgSessionsInObjectCache && !$wgSessionsInMemcached) {
	$wgSessionName = ini_get('session.name');
}
```

`$wgSessionName` is `false` by default, so by checking that is is falsy we still allow for the variable to be overridden.

I'll commit this to master and check it on some sites. The only way this code breaks is if someone changes the value of `session.cookie.name` in their SSP setup to be equal to the PHP session name. I'll add that to the "Known problems" section, as that's a pretty uncommon thing to do.
