### ISSUE TITLE
Requiring SimpleSamlAuth in LocalSettings results in blank page

### ISSUE THREAD

**Issue by va1entin** [jornane/mwSimpleSamlAuth#29]
Hey,
I am looking for a SAML integration for MediaWiki and stumbled upon your extension. I tried it with MW 1.26.2 (most recent) and putting the line

`require_once "$IP/extensions/SimpleSamlAuth/SimpleSamlAuth.php";`

into LocalSettings.php results in MW only showing blank pages afterwards.
Is this a known issue by any chance?

PHP 5.4.45
UCS 4.1-1 (based on Debian 7)

Thanks in advance!

**Comment by jornane** [comment]
Your server logs should tell you why. Blank page usually means an error has occurred, but the error is hidden from the user.

**Comment by va1entin** [comment]
Alright thanks a lot for the quick answer!

I checked the logs and saw that the extension did not have enough rights on a certain file. I gave it access to that but I am still getting this error here
PHP Notice:  MemcachePool::set(): Server unix:///var/run/univention-saml/memcached.socket (tcp 0, udp 0) failed with: Permission denied (13) in /usr/share/simplesamlphp/lib/SimpleSAML/Memcache.php on line 134

Do you mind specifying which permissions the extension needs on which files or which component fails here? 

Thanks in advance!

**Comment by jornane** [comment]
The error occurred in simplesamlphp, so there's not much I can do for you. They have good documentation at https://simplesamlphp.org. In your case it looks like you're trying to set up memcache so I suggest you read https://simplesamlphp.org/docs/latest/simplesamlphp-maintenance#section_2_1

Please be aware that this extension does not need memcache in order to function, you have enabled it yourself somehow.

Since this issue clearly isn't related to the extension, I'm closing this issue.
