### ISSUE TITLE
Mediawiki 1.27 and SimpleSamlphp

### ISSUE THREAD

**Issue by PeteOlsenIII** [jornane/mwSimpleSamlAuth#39]
I have simplesamlphp working with my system but I cannot get mediawiki to recognize the session and log me in. Any ideas?
Thanks,
P

**Comment by jornane** [comment]
From README.md:

**IMPORTANT** If you run MediaWiki 1.27 or newer, SimpleSamlPhp **MUST** be configured to use an alternative session handler.
If this is not done, SAML authentication succeeds, but MediaWiki still shows that nobody is logged in.
Please refer to [the SimpleSamlPhp website](//simplesamlphp.org/docs/stable/simplesamlphp-maintenance) on how to configure SimpleSamlPhp for session storage.

**Comment by PeteOlsenIII** [comment]
Jornane,
  Thanks for the reply. I have set things up so that the session names should be different however I am having the same issue with Mediawiki.

**Comment by jornane** [comment]
The problem is that MediaWiki from version 1.27 uses a different session handler, which conflicts with SimpleSamlPhp's session handler. Even if you set different session names, you can't share the session between the two. Therefore you must use another session handler in SimpleSamlPhp, for example memcache.

**Comment by jartes** [comment]
@jornane I've switched to 'sql' session handler but the extension doesn't create MediaWiki local users for new users. How can we handle this? If I log in with a user that exists locally it works. Thanks!

**Comment by jornane** [comment]
What did you set `$wgSamlCreateUser` to?
